package umgc.mscs495.libmngntsys.screens.book;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.time.LocalDateTime;

import umgc.mscs495.libmngntsys.DAO.BooksDAOimplement;
import umgc.mscs495.libmngntsys.utils.*;
import umgc.mscs495.libmngntsys.vo.BookReservation;

/**
*
* @author ianvi
*/
public class Book1Reserve extends javax.swing.JFrame {

   /**
    * Creates new form Book1Reserve
    */
   public Book1Reserve() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       jLabel1 = new javax.swing.JLabel();
       barcodeField = new javax.swing.JTextField();
       jLabel2 = new javax.swing.JLabel();
       memberIDField = new javax.swing.JTextField();
       reserveBook = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
       setTitle("Reserve Book");

       jLabel1.setText("Book Barcode:");

       jLabel2.setText("Member ID:");

//       memberIDField.addActionListener(new java.awt.event.ActionListener() {
//           public void actionPerformed(java.awt.event.ActionEvent evt) {
//               MemberIDFieldActionPerformed(evt);
//           }
//       });

       reserveBook.setText("ENTER");
       
       reserveBook.addActionListener(e -> reserveBook()); 

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(108, 108, 108)
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jLabel1)
                           .addComponent(jLabel2)
                           .addComponent(memberIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                           .addComponent(barcodeField)))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(159, 159, 159)
                       .addComponent(reserveBook)))
               .addContainerGap(125, Short.MAX_VALUE))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(46, 46, 46)
               .addComponent(jLabel1)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(barcodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jLabel2)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(memberIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(reserveBook)
               .addContainerGap(119, Short.MAX_VALUE))
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );

       pack();
   }// </editor-fold>//GEN-END:initComponents
   
   private void reserveBook() {
	   String bookID = barcodeField.getText();
	   String memberID = memberIDField.getText();
//	   int memberID = parseInt(memberIDField.getText());
	   
	   if(bookID.isEmpty() || memberID.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Please fill one of the fields.");
			
	   } else {
		   BookReservation bookreserve = new BookReservation();
		   bookreserve.setBarcode(bookID);
		   bookreserve.setMemberID(memberID);
		   bookreserve.setCreateDate(LocalDateTime.now().toString());
		   bookreserve.setDueDate(LocalDateTime.now().plusMonths(1).toString());
		   BooksDAOimplement bookimplement = new BooksDAOimplement();
		   bookimplement.reserve(bookreserve);
//		   reserveBook.addActionListener(new java.awt.event.ActionListener() {
//	            public void actionPerformed(java.awt.event.ActionEvent evt) {
//	                reserveBookActionPerformed(evt);
//	            }
//	        });
			
//			return;
		}
		
//		reserveBookInDatabase(bookID, memberID);
		
			
	}
   
   private void reserveBookInDatabase(String bookID, String memberID) {
   	
       try {
       	  Connection connection = LibLibrarianDatabaseConnection.getConnection();

           String sql = "SELECT * FROM LibraryDb.books WHERE";
           
  
           connection.close();
       } catch (SQLException e) {
           e.printStackTrace();
           JOptionPane.showMessageDialog(this, "Error finding book in the database.");
       }
   	
   }

   private void reserveBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveBookActionPerformed
       // Opens Book1SearchResults Frame
       Book1ReserveReturn f2 = new Book1ReserveReturn();  // Creates Frame 2 Book1SearchResults
       f2.setVisible(true);
       // Hides the current JFrame Object
       this.setVisible(false);
   }//GEN-LAST:event_reserveBookActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(Book1Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(Book1Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(Book1Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(Book1Reserve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new Book1Reserve().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField barcodeField;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JTextField memberIDField;
   private javax.swing.JButton reserveBook;
   // End of variables declaration//GEN-END:variables
}
